[package]
name = "iris"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.41.1", features = ["full"] }
thiserror = "2.0.10"
serde = { version = "1.0.215", features = ["derive"] }
redis = "0.29.0"